/*Screen*/

#define DIRECTINPUT_VERSION 0x0800

#define WINDOW_CLASS_NAME L"CastleVania"
#define MAIN_WINDOW_TITLE L"04 - Collision"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(68, 130, 255)
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define MAX_FRAME_RATE 120

/*Simon*/
#define ID_SIMON_TEX	0

#define SIMON_WIDTH		32
#define SIMON_HEIGHT	62

#define LIMIT_SRCEEN_LEFT	0
#define LIMIT_SRCEEN_RIGHT	590
#define GROUND_HEIGHT		250
#define	SIMON_COLOR			D3DCOLOR_XRGB(255, 0, 255)

#define SIMON_WALKING_SPEED		0.1f
#define SIMON_JUMP_SPEED_Y		0.3f
#define SIMON_GRAVITY			0.01f
#define LIMIT_JUMP_HEIGHT	230
#define JUMP_FAR			0.1f

#define SIMON_STATE_IDDLE	0
#define SIMON_STATE_WALK	1
#define SIMON_STATE_ATTACK	2
#define SIMON_STATE_SIT		3
#define SIMON_STATE_JUMP	4
#define SIMON_STATE_SIT_ATTACK	5
#define SIMON_STATE_JUMP_TO	6

#define SIMON_ANI_IDLE_RIGHT		0
#define SIMON_ANI_IDLE_LEFT			1
#define SIMON_ANI_WALKING_RIGHT		2
#define SIMON_ANI_WALKING_LEFT		3
#define SIMON_ANI_ATTACK_LEFT		4
#define SIMON_ANI_ATTACK_RIGHT		5
#define SIMON_ANI_JUMP_RIGHT		6
#define SIMON_ANI_JUMP_LEFT			7
#define SIMON_ANI_SIT_LEFT 			7
#define SIMON_ANI_SIT_RIGHT			6
#define SIMON_ANI_SIT_ATTACK_RIGHT	8
#define	SIMON_ANI_SIT_ATTACK_LEFT	9

/*Whip*/
#define ID_WHIP_TEX		1

#define WHIP_I_ANI_BEHIND_SIMON_STAND_RIGHT	0
#define WHIP_I_ANI_FRONT_SIMON_STAND_RIGHT	1
#define WHIP_I_ANI_BEHIND_SIMON_STAND_LEFT	2
#define WHIP_I_ANI_FRONT_SIMON_STAND_LEFT	3

#define WHIP_I_ANI_SIMON_STAND_RIGHT	0

/*StaticObject*/
/*Movingobject*/
/*Item*/
